clear all;
close all;
clc;

k=[1,3,5,7,9];

a=1;
b=10.^k;
c=1;

%% part a
xp = quad_p2a(a,b,c);
latextable([cellstr(num2str(abs(k'))), num2cell(xp')], ...
            'Horiz',{'$k$','$x_+$'},...
            'name','report/table2a_roots.tex',...
            'format','%10.5e')
        
latextable([cellstr(num2str(abs(k'))), num2cell((a*xp.^2 +2*b.*xp +c )')], ...
       'Horiz',{'$k$','$p(x_+)$'},...
       'name','report/table2a_value.tex',...
       'format','%10.5e')
   
%% part b
xp = quad_p2b(a,b,c);
latextable([cellstr(num2str(abs(k'))), num2cell(xp')], ...
            'Horiz',{'$k$','$x_+$'},...
            'name','report/table2b_roots.tex',...
            'format','%10.5e')

latextable([cellstr(num2str(abs(k'))), num2cell((a*xp.^2 +2*b.*xp +c )')], ...
       'Horiz',{'$k$','$p(x_+)$'},...
       'name','report/table2b_value.tex',...
       'format','%10.5e')